### ISSUE TITLE
Should type `number` fail on NaN?

### ISSUE THREAD

**Issue by davezuko** [TechnologyAdvice/obey#14]
Just browsin' through the source code and wanted to point it out just in case it wasn't intentional:

https://github.com/TechnologyAdvice/obey/blob/master/src/types/number.js
```js
export default (context) => {
  if (typeof context.value !== 'number') {
    context.fail('Value must be a number')
  }
}
```

```js
import isNumber from 'types/number'

isNumber(Number('foo')) // passes
```

If `NaN` isn't handled here, perhaps an additional type to catch this case? I've been bitten by this in the past and didn't want it to slip through.

**Comment by Fluidbyte** [comment]
Yeah, it was on the todo list in my head, thanks for the issue!
