### ISSUE TITLE
Add 'empty' global validator property

### ISSUE THREAD

**Issue by TomFrost** [TechnologyAdvice/obey#22]
If true, empty strings are allowed. If false, field must contain something, or be undefined/null (if not required). Default to false.

**Comment by Fluidbyte** [comment]
This applies to more than just `string` type, also natively `arrays`, but moreover any string-based custom types. Proposal is to add this as a `validator` and definition property.

**Comment by TomFrost** [comment]
Agreed! Changing title to reflect.
