### ISSUE TITLE
Fields not required failing

### ISSUE THREAD

**Issue by Fluidbyte** [TechnologyAdvice/obey#25]
Despite setting `required: false` the following fails `lname` because the `type` check runs and fails. Need to only check present fields, then run check if `required` fields are missing.

```javascript
const test = obey.model({
    fname: { type: 'string' },
    lname: { type: 'string', required: false }
});

test.validate({ fname: 'bob' })
```

**Comment by Fluidbyte** [comment]
Suggested approach is to default `required: false`, then when running [`validate`](https://github.com/TechnologyAdvice/obey/blob/master/src/rules.js#L39) if the definition doesn't specify `required: true` **and** the value is undefined only run `generator` and `default` props; still allowing a default or generated value to be built but if not specified and not required just moving on.

@TomFrost - thoughts?

**Comment by Fluidbyte** [comment]
The above commit [2752492](https://github.com/TechnologyAdvice/obey/commit/2752492bd5f5c60862bb461948f9f804f8c23191) looks to be working when I run it. Need to write tests and clean up a bit.

**Comment by TomFrost** [comment]
Sounds sane!
