### ISSUE TITLE
String type assertion incorrectly fails for empty strings

### ISSUE THREAD

**Issue by davezuko** [TechnologyAdvice/obey#40]
The type checker for a `string` currently also requires the string to have a length greater than 0. This causes issues for string fields that are not required (read: do not need to have any content).

https://github.com/TechnologyAdvice/obey/blob/master/src/typeStrategies/string.js:

````js
  default: context => {
    if (typeof context.value !== 'string' || context.value.length === 0) {
      context.fail('Value must be a string')
    }
  },
```

**Comment by TomFrost** [comment]
This is by design :) Generally when you want a string, you want string content, so this str.length > 0 check is done by default. However, if you want to _allow_ empty strings, just set `empty: true` in the definition: https://github.com/TechnologyAdvice/obey#definition-properties

**Comment by davezuko** [comment]
Seems a bit like it's mixing concerns for a type checker to verify the existence/required-ness of something (it's an odd exception for strings, since normally if a value matches a type it is also truthy). If this is going to remain as is I'll make an appropriate followup issue to the problematic model definition.

/cc @Fluidbyte

**Comment by davezuko** [comment]
Closing as invalid.
