### ISSUE TITLE
More permissive email regex

### ISSUE THREAD

**Issue by levithomason** [TechnologyAdvice/obey#46]
The [email regex](https://github.com/TechnologyAdvice/obey/blob/d8faf05c36d8948b945fbb7055324b791f186770/src/typeStrategies/email.js#L3) included with obey does not match many valid emails.  I've created a regexr with valid email addresses for example: http://regexr.com/3d9cg

This was copied to one of our FE apps for validation, though it is too restrictive to use for validation as it would prevent users from submitting valid email addresses.  We may use it as a warning, but I think we should consider a more permissive rule that does not rule out valid email addresses.  If we can get a rule that does not rule out _any_ valid email, then we can use it for submission validation.

**Comment by davezuko** [comment]
I'm not sure how many of those examples are actually valid email addresses, though a few of them are valid (such as ones with `+` signs). That said, all for a more "correct" approach.

**Comment by levithomason** [comment]
It also says this is valid: `a@b.co`

**Comment by davezuko** [comment]
FYI I believe `a@b.co` is valid unless you're requiring a minimum length on the username. TLD's such as `.me` exist (and `.co`, speaking of which).

**Comment by levithomason** [comment]
Thanks, updated!

>I'm not sure how many of those examples are actually valid email addresses or should even be permissable (No TLD?) but a few of them are valid...

I believe they are all valid per the specs, hence the common wisdom to avoid writing email regex validation.  Also, this is why Google chrome doesn't require a TLD on it's email input validation.

[Try it here](http://www.wufoo.com/html5/types/1-email.html?email=&email2=).
![http://g.recordit.co/Gu8x088afa.gif](http://g.recordit.co/Gu8x088afa.gif)

Here is a great article on this: https://davidcel.is/posts/stop-validating-email-addresses-with-regex/

>...Sections [3.2.4](https://tools.ietf.org/html/rfc2822#section-3.2.4) and [3.4.1](https://tools.ietf.org/html/rfc2822#section-3.4.1) of the RFC go into the requirements on how an email address needs to be formatted and, well, there’s not much you can’t do in your email address when quotes or backslashes are involved. The local string (the part of the email address that comes before the @) can contain any of these characters: ! $ & * - = ^ ` | ~ # % ' + / ? _ { }
>
>But guess what? You can use pretty much any character you want if you escape it by surrounding it in quotes. For example, "Look at all these spaces!"@example.com is a valid email address. Nice.

From which I took this regex `.+@.+\..+` that seems to allow the label and far more other valid cases, seen here http://regexr.com/3d9cs

**Comment by levithomason** [comment]
Lastly, here is a super popular and well supported email validator.  We ought to consider it:

https://github.com/mailcheck/mailcheck
