### ISSUE TITLE
read-only field as an option

### ISSUE THREAD

**Issue by frankleng** [TechnologyAdvice/obey#50]
Useful when enforcing fields that cannot be changed

**Comment by Fluidbyte** [comment]
I apologize, I just saw this, could you give an example?

**Comment by frankleng** [comment]
@Fluidbyte no worries. thanks for the great lib.
I have a use case where a field is set on creation, and should not be modified afterwards. so would like to have a validation error when user is trying to update.

tho I think I might be able to workaround by using a modifier callback

**Comment by Fluidbyte** [comment]
I've been thinking about this and it wouldn't really be possible at the level where Obey resides since it has no inherit knowledge of if data is going through a create or update process. You'd probably be best simply running a check inside the CRUD methods themselves.
