### ISSUE TITLE
Custom methods on model?

### ISSUE THREAD

**Issue by fridays** [TechnologyAdvice/obey#53]
Hi, this project looks great!

Is it possible to add custom methods to a model, something like the following?

```
userModel.methods.getFullName = function() {
    return this.fname + ' ' + this.lname;
}
```

**Comment by ummjackson** [comment]
+1, would love to know if this is in the future of Obey.js 👍

**Comment by ummjackson** [comment]
Just found https://github.com/node-modli/modli created by the same maintainers as Obey 💯

**Comment by Fluidbyte** [comment]
There isn't any built-in way to do this as it stands, however, as @ummjackson shared, Modli (built by our team) is a full CRUD solution which extends on Obey to allow for doing things like this.

Given `getFullName` is more a function of a data read action, and not so much one of validation, I would see it better placed outside the scope of Obey. You could do something as simple as:

```javascript
const user = {
  schema: obey.model({
    fname: { type: 'string' },
    lname: { type: 'string' }
  }),
  getFullName: (data) => {
    return data.fname + ' ' + data.lname
  },
  read: () => {
    return db.read({...})
  }
  /* ...other custom methods... */
}
```

The above is essentially what Modli does, just creating a model object with other methods associated, then on `create` and `update` we just run the data through the `schema`'s `validate` method beforehand.

**Comment by Fluidbyte** [comment]
I'm willing to reopen this if there's a sound argument for including this functionality, or simply to discuss further. However, for now I'm going to close it.
