### ISSUE TITLE
New feature request: "equalsTo" validator

### ISSUE THREAD

**Issue by devsli** [TechnologyAdvice/obey#58]
When I validate registration form, I want to validate password confirmation with schema like this:
```js
let model = obey.model({
	/* Unrelated fields omitted */
	password: {
		type: 'string',
		min: 8
	},
	passwordConfirm: {
		type: 'string',
		equalsTo: 'password'
	}
});
```

**Comment by Fluidbyte** [comment]
This makes a lot of sense, the new conditional requires (`requireIf`, `requireIfNot`) exposes a `initData` property in the [/src/rules.js](https://github.com/TechnologyAdvice/obey/pull/56/files#diff-e1e485869309483077d12d0f82e79856R94) file which could make this pretty simple to accomplish.

Someone on our team will take a look at implementing this as time allows, or feel free to submit a PR if you feel so inclined 😄

**Comment by devsli** [comment]
Hi @Fluidbyte! No problem, I'll submit PR soon.

**Comment by Fluidbyte** [comment]
[Minor version release 1.6.0](https://github.com/TechnologyAdvice/obey/releases/tag/v1.6.0) just published. Thanks for your contribution!
