### ISSUE TITLE
initData is not updated

### ISSUE THREAD

**Issue by devsli** [TechnologyAdvice/obey#59]
When you use `requireIf`, `requireIfNot` or `equalsTo` (soon) then you may find weird issue - first value of referenced fields are not updated.

### Example

```js
let schema = obey.model({
	phone: { type: "string" },
	phoneType: { type: "string", requireIf: "phone" }
});

schema.validate({ phone: "123" }).then(() => {
	console.error('Bad: Form is invalid, you should not see this message')
})
.catch(() => {

	let muchNewSchema = obey.model({
		phone: { type: "string" },
		phoneType: { type: "string", requireIf: "phone" }
	});

	muchNewSchema.validate({}).then(() => {
		console.log('Good: Bug is fixed');
	})
	.catch((e) => {
		console.error('Bad: Form is valid, you should not see this message');
		console.error(e.message);
	})

})
```

Result:

```diff
- Bad: Form is valid, you should not see this message
- phoneType (undefined): Value required because 'phone' exists
```

The problem is when you run validation second time - `obey.rules.initData` is already set so it doesn't updated.
https://github.com/TechnologyAdvice/obey/blob/master/src/rules.js#L85

**Comment by Fluidbyte** [comment]
Can you just remove the conditional `if (!rules.initData)` and just always set/override it? I'm writing this between family activities for the holiday, so double-check my logic there, but hopefully keeps things moving on your end.

**Comment by Fluidbyte** [comment]
My only concern would be the lifespan of that, since the whole library is promised-based 2 simultaneous calls to `validate` could cause issues as `initData` would be set for the library and not each run...

**Comment by Fluidbyte** [comment]
Looping in @psvet on this since he wrote the `requiredIf` and `requiredIfNot` updates
